#!/bin/sh

outdir=/mnt/a

if [ ! -d $outdir/osm ]; then
    mkdir $outdir/osm
fi

if [ ! -d $outdir/osm/pbf ]; then
    mkdir $outdir/osm/pbf
fi

curl -L https://download.geofabrik.de/europe/switzerland-latest.osm.pbf -o $outdir/osm/pbf/switzerland.pbf
curl -L https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf      -o $outdir/osm/pbf/planet.pbf
