#!/bin/sh


if [ ! -d ~/osm ]; then
    mkdir ~/osm
fi

if [ ! -d ~/osm/pbf ]; then
    mkdir ~/osm/pbf
fi

curl -L https://download.geofabrik.de/europe/switzerland-latest.osm.pbf -o ~/osm/pbf/switzerland.pbf
curl -L https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf      -o ~/osm/pbf/planet.pbf
